//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bioskop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Glumacs = new HashSet<Glumac>();
            this.Prikazujes = new HashSet<Prikazuje>();
        }
    
        public int IdFilma { get; set; }
        public decimal Trajanje { get; set; }
        public string Zanr { get; set; }
        public string Naziv { get; set; }
        public Nullable<int> RepertoarIdRepertoara { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Glumac> Glumacs { get; set; }
        public virtual Repertoar Repertoar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prikazuje> Prikazujes { get; set; }
    }
}
