//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bioskop.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<Menadzer> Radniks_Menadzer { get; set; }
        public virtual DbSet<Blagajnik> Radniks_Blagajnik { get; set; }
        public virtual DbSet<Cistacica> Radniks_Cistacica { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
        public virtual DbSet<Sjediste> Sjedistes { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Glumac> Glumacs { get; set; }
        public virtual DbSet<Prikazuje> Prikazujes { get; set; }
        public virtual DbSet<Repertoar> Repertoars { get; set; }
        public virtual DbSet<Posjetilac> Posjetilacs { get; set; }
        public virtual DbSet<Karta> Kartas { get; set; }
        public virtual DbSet<Sadrzi> Sadrzis { get; set; }
    }
}
