//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bioskop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posjetilac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posjetilac()
        {
            this.Kartas = new HashSet<Karta>();
        }
    
        public int IdPosjetioca { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int BlagajnikIdRadnika { get; set; }
    
        public virtual Blagajnik Blagajnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karta> Kartas { get; set; }
    }
}
